package rules;

import com.bsep.recipes.dto.RecipeDTO
import com.bsep.recipes.model.Recipe
import com.bsep.recipes.model.RecipeComplexityType;

rule "New easy recipe"
	agenda-group "new-recipe"
	when 
		$recipeDTO: RecipeDTO(steps.size()<4)
		$recipe : Recipe(complexity==null)
	then
		$recipe.setComplexity(RecipeComplexityType.EASY);
		update($recipe)
end

rule "New hard recipe"
	agenda-group "new-recipe"
	when 
		$recipeDTO: RecipeDTO(steps.size()>7)
		$recipe : Recipe(complexity==null)
	then
		$recipe.setComplexity(RecipeComplexityType.HARD);
		update($recipe)
end

rule "New medium recipe"
	agenda-group "new-recipe"
	when 
		$recipeDTO: RecipeDTO(steps.size()<=7, steps.size()>=4)
		$recipe : Recipe(complexity==null)
	then
		System.out.println("HEJ2");
		$recipe.setComplexity(RecipeComplexityType.MEDIUM);
		update($recipe)
end
