package rules;

import com.bsep.recipes.model.RegisteredUser;
import com.bsep.recipes.model.Recipe;
import com.bsep.recipes.model.RecipeComplexityType;
import com.bsep.recipes.model.UserKnowledgeType;
import com.bsep.recipes.model.Grade;

rule "Upgrade user to medium"
	when 
		$user : RegisteredUser($grades: grades, knowledge == UserKnowledgeType.BEGINER) @Watch (grades)
		$n: Number(intValue==2) from accumulate (
    	 						$g : Grade(
    	 							grade >= 4,
    	 							recipe.complexity == RecipeComplexityType.EASY
    	 						)	 
    	 						from $grades,
    	 						count($g)
    	 					)
	then
		System.out.println($grades);
		System.out.println($n);
		$user.setKnowledge(UserKnowledgeType.INTERMEDIATE);
end

rule "Upgrade user to advanced"
	when 
		$user : RegisteredUser($grades: grades, knowledge == UserKnowledgeType.INTERMEDIATE) @Watch (grades)
		$n: Number(intValue==3) from accumulate (
    	 						$g: Grade(
    	 							grade >= 4,
    	 							recipe.complexity == RecipeComplexityType.MEDIUM
    	 						)	 
    	 						from $grades,
    	 						count($g)
    	 					)
	then
		System.out.println($grades);
		System.out.println($n);
		$user.setKnowledge(UserKnowledgeType.ADVANCED);
end

//new rules

